# CircleCI 2.0 configuration file for running Twisted checks.
#
# Email notifications are configured only from web.
# See "Email Preferences by Organization" in
# https://circleci.com/account/notifications
#
# Based on these v1.0 steps:
# https://pewpewthespells.com/blog/building_python_on_circleci.html
#
# This uses the v2 workflows and a separate commit status is sent for each
# job.
#
# CircleCI 2.0 automatically sets a $BASH_ENV variable to a
# random name in /tmp, and will source this file for each step.
#
version: 2

jobs:
  wheel:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout

      - run:
          name: Prepare the environment.
          command: |
            python --version
            python -m venv venv
            venv/bin/pip install -r requirements.txt

      - run:
          name: Build the wheel.
          command: |
            venv/bin/python setup.py bdist_wheel --dist-dir=dist
            venv/bin/python setup.py sdist --formats=gztar,zip --dist-dir=dist

      - run:
          name: Deploy to PyPI.
          command: |
            venv/bin/python twineversioneer.py upload dist/*

      - store_artifacts:
          path: dist/

workflows:
  version: 2
  all:
    jobs:
      - wheel
